<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    
    <title>Cnc25D API &mdash; Cnc25D 0.1.3 documentation</title>
    
    <link rel="stylesheet" href="_static/haiku.css" type="text/css" />
    <link rel="stylesheet" href="_static/pygments.css" type="text/css" />
    <link rel="stylesheet" href="_static/print.css" type="text/css" />
    
    <script type="text/javascript">
      var DOCUMENTATION_OPTIONS = {
        URL_ROOT:    './',
        VERSION:     '0.1.3',
        COLLAPSE_INDEX: false,
        FILE_SUFFIX: '.html',
        HAS_SOURCE:  true
      };
    </script>
    <script type="text/javascript" src="_static/jquery.js"></script>
    <script type="text/javascript" src="_static/underscore.js"></script>
    <script type="text/javascript" src="_static/doctools.js"></script>
    <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
    <script type="text/javascript" src="_static/theme_extras.js"></script>
    <link rel="top" title="Cnc25D 0.1.3 documentation" href="index.html" />
    <link rel="next" title="Box Wood Frame Design" href="box_wood_frame_design.html" />
    <link rel="prev" title="Cnc25D Presentation" href="cnc25d_presentation.html" /> 
  </head>
  <body>
      <div class="header"><h1 class="heading"><a href="index.html">
          <span>Cnc25D 0.1.3 documentation</span></a></h1>
        <h2 class="heading"><span>Cnc25D API</span></h2>
      </div>
      <div class="topnav">
      
        <p>
        «&#160;&#160;<a href="cnc25d_presentation.html">Cnc25D Presentation</a>
        &#160;&#160;::&#160;&#160;
        <a class="uplink" href="index.html">Contents</a>
        &#160;&#160;::&#160;&#160;
        <a href="box_wood_frame_design.html">Box Wood Frame Design</a>&#160;&#160;»
        </p>

      </div>
      <div class="content">
        
        
  <div class="section" id="cnc25d-api">
<h1>Cnc25D API<a class="headerlink" href="#cnc25d-api" title="Permalink to this headline">¶</a></h1>
<div class="section" id="cnc25d-workflow">
<h2>1. Cnc25D Workflow<a class="headerlink" href="#cnc25d-workflow" title="Permalink to this headline">¶</a></h2>
<p><strong>FreeCAD</strong> provides many GUI and API functions to sculpt and assemble 3D designs. <strong>Cnc25D</strong> proposes a script methodology and an API on top of the <a class="reference external" href="http://free-cad.sourceforge.net/api/index.html">FreeCAD API</a> to design 2.5D parts.</p>
<img alt="_images/cnc25d_design_workflow.png" src="_images/cnc25d_design_workflow.png" />
<div class="section" id="the-cnc25d-methodology">
<h3>The Cnc25D methodology<a class="headerlink" href="#the-cnc25d-methodology" title="Permalink to this headline">¶</a></h3>
<p>1. Create a list of 2D points you want that your outline go through.
An outline is a list of lines and/or arcs. Other curve type must be generated by using multiple small lines.</p>
<p>2. Enlarge or Smooth the corners of the outline to do it makeable by a 3-axis CNC.
The cnc25d_api.cnc_cut_outline() function do it for you.
It returns a new list of 2D points defining the new lines and arcs of the new outline.</p>
<p>3. Exploit the 2D outline.
This new outline can already be export as SVG or DXF.
It can also be displayed using Tkinter.
Finally, it can be converted intor FreeCAD Part outline to be extruded in 3D part.</p>
<p>4. Create your 3D assembly.
After creating the 3D parts with the FreeCAD Part API, cnc25d_api.place_plank() provides a more natural way to place 3D parts in an assembly than the standard rotate() and translate() methods.</p>
<p>5. Export your design.
Export a cut of a 3D parts with cnc25d_api.export_2d().
Get a 3D scanning of your assembly with cnc25d_api.export_xyz_to_dxf()</p>
</div>
</div>
<div class="section" id="cnc25d-api-functions-and-class">
<h2>2. Cnc25D API functions and class<a class="headerlink" href="#cnc25d-api-functions-and-class" title="Permalink to this headline">¶</a></h2>
<div class="highlight-python"><div class="highlight"><pre><span class="n">cnc25d_api</span><span class="o">.</span><span class="n">importing_freecad</span><span class="p">()</span>
<span class="n">cnc25d_api</span><span class="o">.</span><span class="n">outline_shift_x</span><span class="p">(</span><span class="n">outline_AB</span><span class="p">,</span> <span class="n">x</span><span class="o">-</span><span class="n">offset</span><span class="p">,</span> <span class="n">x</span><span class="o">-</span><span class="n">coefficient</span><span class="p">)</span>
<span class="n">cnc25d_api</span><span class="o">.</span><span class="n">outline_shift_y</span><span class="p">(</span><span class="n">outline_AB</span><span class="p">,</span> <span class="n">y</span><span class="o">-</span><span class="n">offset</span><span class="p">,</span> <span class="n">y</span><span class="o">-</span><span class="n">coefficient</span><span class="p">)</span>
<span class="n">cnc25d_api</span><span class="o">.</span><span class="n">outline_shift_xy</span><span class="p">(</span><span class="n">outline_AB</span><span class="p">,</span> <span class="n">x</span><span class="o">-</span><span class="n">offset</span><span class="p">,</span> <span class="n">x</span><span class="o">-</span><span class="n">coefficient</span><span class="p">,</span> <span class="n">y</span><span class="o">-</span><span class="n">offset</span><span class="p">,</span> <span class="n">y</span><span class="o">-</span><span class="n">coefficient</span><span class="p">)</span>
<span class="n">cnc25d_api</span><span class="o">.</span><span class="n">outline_rotate</span><span class="p">(</span><span class="n">outline_AB</span><span class="p">,</span> <span class="n">center</span><span class="o">-</span><span class="n">x</span><span class="p">,</span> <span class="n">center</span><span class="o">-</span><span class="n">y</span><span class="p">,</span> <span class="n">rotation_angle</span><span class="p">)</span>
<span class="n">cnc25d_api</span><span class="o">.</span><span class="n">outline_close</span><span class="p">(</span><span class="n">outline_AB</span><span class="p">)</span>
<span class="n">cnc25d_api</span><span class="o">.</span><span class="n">outline_reverse</span><span class="p">(</span><span class="n">outline_AB</span><span class="p">)</span>
<span class="n">cnc25d_api</span><span class="o">.</span><span class="n">cnc_cut_outline</span><span class="p">(</span><span class="n">outline_A</span><span class="p">,</span> <span class="n">mark_string</span><span class="p">)</span>
<span class="n">cnc25d_api</span><span class="o">.</span><span class="n">outline_arc_line</span><span class="p">(</span><span class="n">outline_B</span><span class="p">,</span> <span class="n">backend</span><span class="p">)</span>
<span class="n">cnc25d_api</span><span class="o">.</span><span class="n">outline_circle</span><span class="p">((</span><span class="n">center</span><span class="o">-</span><span class="n">x</span><span class="p">,</span> <span class="n">center</span><span class="o">-</span><span class="n">y</span><span class="p">),</span> <span class="n">radius</span><span class="p">,</span> <span class="n">backend</span><span class="p">)</span>
<span class="n">cnc25d_api</span><span class="o">.</span><span class="n">Two_Canvas</span><span class="p">(</span><span class="n">Tkinter</span><span class="o">.</span><span class="n">Tk</span><span class="p">())</span> <span class="c"># object constructor</span>
<span class="n">cnc25d_api</span><span class="o">.</span><span class="n">place_plank</span><span class="p">(</span><span class="n">freecad_part_object</span><span class="p">,</span> <span class="n">x</span><span class="o">-</span><span class="n">size</span><span class="p">,</span> <span class="n">y</span><span class="o">-</span><span class="n">size</span><span class="p">,</span> <span class="n">z</span><span class="o">-</span><span class="n">size</span><span class="p">,</span> <span class="n">flip</span><span class="p">,</span> <span class="n">orientation</span><span class="p">,</span> <span class="n">x</span><span class="o">-</span><span class="n">position</span><span class="p">,</span> <span class="n">y</span><span class="o">-</span><span class="n">position</span><span class="p">,</span> <span class="n">z</span><span class="o">-</span><span class="n">position</span><span class="p">)</span>
<span class="n">cnc25d_api</span><span class="o">.</span><span class="n">export_to_dxf</span><span class="p">(</span><span class="n">freecad_part_object</span><span class="p">,</span> <span class="n">direction_vector</span><span class="p">,</span> <span class="n">depth</span><span class="p">,</span> <span class="n">filename</span><span class="p">)</span>
<span class="n">cnc25d_api</span><span class="o">.</span><span class="n">export_xyz_to_dxf</span><span class="p">(</span><span class="n">freecad_part_object</span><span class="p">,</span> <span class="n">x</span><span class="o">-</span><span class="n">size</span><span class="p">,</span> <span class="n">y</span><span class="o">-</span><span class="n">size</span><span class="p">,</span> <span class="n">z</span><span class="o">-</span><span class="n">size</span><span class="p">,</span> <span class="n">x</span><span class="o">-</span><span class="n">depth</span><span class="o">-</span><span class="nb">list</span><span class="p">,</span> <span class="n">y</span><span class="o">-</span><span class="n">depth</span><span class="o">-</span><span class="nb">list</span><span class="p">,</span> <span class="n">z</span><span class="o">-</span><span class="n">depth</span><span class="o">-</span><span class="nb">list</span><span class="p">,</span> <span class="n">filename</span><span class="p">)</span>
</pre></div>
</div>
</div>
<div class="section" id="cnc25d-outline-creation">
<h2>3. Cnc25D outline creation<a class="headerlink" href="#cnc25d-outline-creation" title="Permalink to this headline">¶</a></h2>
<div class="section" id="cnc25d-outline">
<h3>3.1. Cnc25D outline<a class="headerlink" href="#cnc25d-outline" title="Permalink to this headline">¶</a></h3>
<p>Cnc25D helps you to work on outline before extruding it into 3D parts. <em>Cnc25D outlines</em> are defined in the XY-plan and consist of a series of lines and/or arcs. A <em>line</em> is defined by a start point and an end point. An <em>arc</em> is defined by a start point, a passing-through point and an end point.</p>
<img alt="_images/outline_example.png" src="_images/outline_example.png" />
<p>Manipulating Cnc25D outline consists of working on 2D points. This requires much less CPU resources as invoking a complete 3D software. If you want to create other types of curve than lines or arcs, you must approximate those curves with multiple small lines.</p>
<p>Cnc25D outline vocabulary:</p>
<ul class="simple">
<li>outline: a series of segments</li>
<li>segment: a line or an arc</li>
<li>start-point: the starting point of a line or an arc</li>
<li>end-point: the ending point of a line or an arc</li>
<li>middle-point: the passing-through point of an arc (it doesn&#8217;t have to be in the middle of the arc)</li>
<li>first-point: the start point of the first segment of an outline</li>
<li>corner: the junction between two consecutive segments.</li>
<li>corner-point: the end-point of the previous segment or the start-point of the next segment</li>
<li><em>rbrr</em> : the router_bit radius request (how to transform a corner to do it millable by a router_bit of radius R?)</li>
<li>closed outline: <em>True</em> if the end-point of the last segment is equal to the first-point</li>
<li>outline orientation: <em>Counter Clock Wise</em> (CCW) or <em>Clock Wise</em> (CW) (this has a meaning only for closed outline)</li>
<li>outline format A: pythonic description of an outline used as argument by the function cnc25d_api.cnc_cut_outline()</li>
<li>outline format B: pythonic description of an outline returned by cnc25d_api.cnc_cut_outline() and used as argument by cnc25d_api.outline_arc_line()</li>
</ul>
<img alt="_images/closed_outline.png" src="_images/closed_outline.png" />
</div>
<div class="section" id="cnc25d-outline-format-a">
<h3>3.2. Cnc25D outline format A<a class="headerlink" href="#cnc25d-outline-format-a" title="Permalink to this headline">¶</a></h3>
<p>In short, the <em>Cnc25D outline format A</em> is a list of list of 3 or 5 floats.</p>
<p>The purpose of the <em>Cnc25D outline format A</em> is to define your wished outline. In addition to the start, middle and end points of the segments, you define for each corner the associated <em>rbrr</em>. That means that you can request different router_bit radius for each corner. In general, you will set the same value for all corners of your outline. But you also have the flexibility to set different <em>rbrr</em> for each corner.</p>
<p>The first element of the <em>outline format A</em> list is the <em>first-point</em>. It is defines by a list of 3 floats: X-coordinate, Y-coordinate and the <em>rbrr</em> of the <em>first-point</em>.</p>
<p>The second element of the <em>outline format A</em> list is the first segment of the outline. If the first segment is a line, it is defines by a list of 3 floats: end-point-X, end-point-Y and the <em>rbrr</em> of the end-point of the segment. If the first segment is an arc, it is defines by a list of 5 floats: middle-point-X, middle-point-Y, end-point-X, end-point-Y and the <em>rbrr</em> of the end-point of the segment.</p>
<p>All elements of the <em>outline format A</em> list define a segment except the first element that defines the <em>first-point</em>. An outline composed of N segments is described by a list of N+1 elements. A segment is defined by 3 floats if it is a line or 5 floats if it is an arc. The start-point of a segment is never explicitly defined as it is the end-point of the previous segment. If the X and Y coordinates of the end-point of the last segment are equal to the X and Y coordinates of the first-point of the outline, the outline is closed.</p>
<p><em>rbrr</em> (a.k.a <em>router_bit radius request</em>) defines how cnc25d_api.cnc_cut_outline() must modify a corner:</p>
<ul class="simple">
<li>if rbrr = 0, the corner is unchanged</li>
<li>if rbrr &gt; 0, the corner is smoothed to fit the router_bit radius <em>rbrr</em></li>
<li>if rbrr &lt; 0, the corner is enlarged to fit the router_bit radius <em>abs(rbrr)</em></li>
</ul>
<p><em>Good practice</em>: If the outline is closed, the <em>rbrr</em> of the last segment must be set to zero. If the outline is open (i.e. not closed), the <em>rbrr</em> of the <em>first-point</em> and the <em>rbrr</em> of the last segment must be set to zero.</p>
<p>The <em>outline format A</em> can be defined with <em>list</em> or <em>tuple</em>. The orientation of a closed outline can be CCW or CW.</p>
<p>outline format A example:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">outline_A</span> <span class="o">=</span> <span class="p">[</span>
  <span class="p">[</span>  <span class="mi">0</span><span class="p">,</span>  <span class="mi">0</span><span class="p">,</span> <span class="mi">10</span><span class="p">]</span>           <span class="c"># first-point</span>
  <span class="p">[</span> <span class="mi">50</span><span class="p">,</span>  <span class="mi">0</span><span class="p">,</span> <span class="mi">15</span><span class="p">]</span>           <span class="c"># horizontal line</span>
  <span class="p">[</span> <span class="mi">43</span><span class="p">,</span> <span class="mi">43</span><span class="p">,</span>  <span class="mi">0</span><span class="p">,</span>  <span class="mi">50</span><span class="p">,</span> <span class="mi">20</span><span class="p">]</span>  <span class="c"># arc</span>
  <span class="p">[</span>  <span class="mi">0</span><span class="p">,</span>  <span class="mi">0</span><span class="p">,</span>  <span class="mi">0</span><span class="p">]]</span>          <span class="c"># vertical line and close the outline</span>
</pre></div>
</div>
<img alt="_images/outline_format_A_example.png" src="_images/outline_format_A_example.png" />
</div>
<div class="section" id="cnc25d-outline-format-b">
<h3>3.3. Cnc25D outline format B<a class="headerlink" href="#cnc25d-outline-format-b" title="Permalink to this headline">¶</a></h3>
<p>In short, the <em>Cnc25D outline format B</em> is a list of list of 2 or 4 floats.</p>
<p>The purpose of the <em>Cnc25D outline format B</em> is to define an outline with points. This is a simplification of the <em>outline format A</em>, where the <em>rbrr</em> information is removed.</p>
<p>The first element of the <em>outline format B</em> list is the <em>first-point</em>. It is defines by a list of 2 floats: X-coordinate, Y-coordinate.</p>
<p>The second element of the <em>outline format B</em> list is the first segment of the outline. If the first segment is a line, it is defines by a list of 2 floats: end-point-X, end-point-Y. If the first segment is an arc, it is defines by a list of 4 floats: middle-point-X, middle-point-Y, end-point-X, end-point-Y.</p>
<p>All elements of the <em>outline format B</em> list define a segment except the first element that defines the <em>first-point</em>. An outline composed of N segments is described by a list of N+1 elements. A segment is defined by 2 floats if it is a line or 4 floats if it is an arc. The start-point of a segment is never explicitly defined as it is the end-point of the previous segment. If the X and Y coordinates of the end-point of the last segment are equal to the X and Y coordinates of the first-point of the outline, the outline is closed.</p>
<p>The <em>outline format B</em> can be defined with <em>list</em> or <em>tuple</em>. The orientation of a closed outline can be CCW or CW.</p>
<p>outline format B example:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">outline_B</span> <span class="o">=</span> <span class="p">[</span>
  <span class="p">[</span>  <span class="mi">0</span><span class="p">,</span>  <span class="mi">0</span><span class="p">]</span>           <span class="c"># first-point</span>
  <span class="p">[</span> <span class="mi">50</span><span class="p">,</span>  <span class="mi">0</span><span class="p">]</span>           <span class="c"># horizontal line</span>
  <span class="p">[</span> <span class="mi">43</span><span class="p">,</span> <span class="mi">43</span><span class="p">,</span>  <span class="mi">0</span><span class="p">,</span>  <span class="mi">50</span><span class="p">]</span>  <span class="c"># arc</span>
  <span class="p">[</span>  <span class="mi">0</span><span class="p">,</span>  <span class="mi">0</span><span class="p">]]</span>          <span class="c"># vertical line and close the outline</span>
</pre></div>
</div>
<img alt="_images/outline_format_B_example.png" src="_images/outline_format_B_example.png" />
</div>
<div class="section" id="the-function-cnc-cut-outline">
<h3>3.4. The function Cnc_cut_outline()<a class="headerlink" href="#the-function-cnc-cut-outline" title="Permalink to this headline">¶</a></h3>
<div class="line-block">
<div class="line"><tt class="docutils literal"><span class="pre">cnc_cut_outline.</span></tt> <strong>cnc_cut_outline(</strong> <em>list, string</em> <strong>)</strong></div>
<div class="line-block">
<div class="line">Return a <em>list</em>.</div>
</div>
</div>
<div class="section" id="cnc-cut-outline-purpose">
<h4>3.4.1. cnc_cut_outline purpose<a class="headerlink" href="#cnc-cut-outline-purpose" title="Permalink to this headline">¶</a></h4>
<p>If you work with 3-axis CNC, your free XY-path gets actually some constraints due to the router_bit diameter. Real inner angle can not be manufacture and must be replaced either by a smoothed angle or an enlarged angle.</p>
<img alt="_images/inner_angle_for_3_axis_cnc.png" src="_images/inner_angle_for_3_axis_cnc.png" />
<p>The <em>cnc_cut_outline</em> function aims at converting an outline defined by a list of points into an outline with lines and arcs makable by a 3-axis CNC. For each point, you choose if you want to enlarge the angle, smooth it or leave it sharp.</p>
<p>Look at the <a class="reference internal" href="cnc_cut_outline.html"><em>CNC Cut Outline</em></a> chapter to get more information on when you should enlarge and when you should smooth a corner angle.</p>
</div>
<div class="section" id="cnc-cut-outline-usage">
<h4>3.4.2. cnc_cut_outline usage<a class="headerlink" href="#cnc-cut-outline-usage" title="Permalink to this headline">¶</a></h4>
<p>The cnc_cut_outline() function provides three possibilites as corner transformation: smooth, unchange, enlarge.</p>
<img alt="_images/cnc_cut_outline_transformations.png" src="_images/cnc_cut_outline_transformations.png" />
<p>If <em>rbrr</em> (a.k.a. router_bit radius request) is positive, the angle is smoothed. If <em>rbrr</em> is negative, the angle is enlarged. If <em>rbrr</em> is zero, the angle is unmodified.</p>
<p><em>Smoothing a corner</em> is a closed problem: there is only one arc of radius R (= <em>rbrr</em>) that is tangent to the two adjacent segments.</p>
<img alt="_images/smoothing_line_line_corner.png" src="_images/smoothing_line_line_corner.png" />
<img alt="_images/smoothing_line_arc_corner.png" src="_images/smoothing_line_arc_corner.png" />
<img alt="_images/smoothing_arc_arc_corner.png" src="_images/smoothing_arc_arc_corner.png" />
<p><em>Enlarging a corner</em> is an open problem: there are several arcs of radius R (= <em>rbrr</em>) that can clear the wished outline. <em>Cnc25D</em> chose the arc of radius R (= <em>rbrr</em>) of which the center is on the line defined by the corner-point and the center of the associated smoothed corner. If you want an other solution, you can modify slightly your wished outline (in format A) to influence the final result as shown in the next paragraph <em>alternative enlarged corner</em>.</p>
<img alt="_images/enlarging_line_line_corner.png" src="_images/enlarging_line_line_corner.png" />
<img alt="_images/enlarging_line_arc_corner.png" src="_images/enlarging_line_arc_corner.png" />
<img alt="_images/enlarging_arc_arc_corner.png" src="_images/enlarging_arc_arc_corner.png" />
<p>Notice that the interior of an closed outline is not influencing the process of smoothing or enlarging a corner. Only the local geometry (namely the two adjacent segments) influence this process.</p>
<p>The <em>cnc_cut_outline()</em> function needs as argument an outline of <em>format A</em> and returns an outline of <em>format B</em>. The <em>format B outline</em> can easily be converted into a FreeCAD Part Object, that can be after some conversions be extruded:</p>
<div class="highlight-python"><pre>my_outline_A = [
  [  0.0 ,  0.0,  0.0],   # this corner will be leaved sharp
  [ 20.0 ,  0.0,  5.0],   # this corner will be smoothed
  [  0.0 , 20.0, -5.0]]   # this corner will be enlarged
my_outline_B = (cnc25d_api.cnc_cut_outline(my_outline_A, "demo_my_outline_A")
my_part_face = Part.Face(Part.Wire(cnc25d_api.outline_arc_line(my_outline_B, 'freecad').Edges))
my_part_solid = my_part_face.extrude(Base.Vector(0,0,20))</pre>
</div>
<p>Look at the script <em>cnc25d_api_example.py</em> that you can generate with the executable <em>cnc25d_example_generator.py</em> for a more complete example.</p>
<p>If the requested <em>router_bit radius</em> is too large, the corner transformation may not be applied because of geometrical constraints. You get a <em>warning</em> or <em>error</em> message containing <em>string</em> set as argument. A good practice is to set <em>string</em> to the function name that calls <em>cnc_cut_outline()</em>. So you can find out which outline is not compatible with the requested <em>router_bit radius</em> in case of error. Below an example of warning message due to a too large <em>router_bit radius</em>. Thanks to the <em>string</em>, we know that the outline issue is located in the <em>plank_z_side</em> function:</p>
<div class="highlight-python"><pre>WARN301: Warning, corner plank_z_side.1 can not be smoothed or enlarged because edges are too short!</pre>
</div>
</div>
<div class="section" id="alternative-enlarged-corner">
<h4>3.4.3. Alternative enlarged corner<a class="headerlink" href="#alternative-enlarged-corner" title="Permalink to this headline">¶</a></h4>
<p>As the problematic of enlarging a corner doesn&#8217;t have a unique solution, you may want an other <em>enlarging corner</em> than the default one proposed by <em>cnc_cut_outline()</em>. For example, you may want to enlarge a corner without milling one of the adjacent segment. By changing the input outline, you can achieve it:</p>
<img alt="_images/alternative_enlarged_corner.png" src="_images/alternative_enlarged_corner.png" />
<p>For comparison, the default result would be:</p>
<img alt="_images/default_enlarged_corner.png" src="_images/default_enlarged_corner.png" />
</div>
</div>
<div class="section" id="other-outline-help-functions">
<h3>3.5. Other outline help functions<a class="headerlink" href="#other-outline-help-functions" title="Permalink to this headline">¶</a></h3>
<p><em>Cnc25D outline format A</em> and <em>B</em> reduce the description of an outline to the 2D coordinates of points. That&#8217;s a drastic reduction of the amount of Data and still keeping the description accurate. But for complex outlines, a large list of point coordinates might become unreadable. It is preferable, to split a large list into comprehensive smaller sub-paths and then concatenate them. Often patterns will be used several times for an outline with some slight modifications like position (of course), scale, mirror or rotation. This is the purpose of the <em>outline help functions</em>.</p>
<p>The <em>outline help functions</em> accept as argument the <em>Cnc25D outline format A</em> and the <em>Cnc25D outline format B</em> and return the outline with the same format:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">cnc25d_api</span><span class="o">.</span><span class="n">outline_shift_x</span><span class="p">(</span><span class="n">outline_AB</span><span class="p">,</span> <span class="n">x</span><span class="o">-</span><span class="n">offset</span><span class="p">,</span> <span class="n">x</span><span class="o">-</span><span class="n">coefficient</span><span class="p">)</span>
<span class="n">cnc25d_api</span><span class="o">.</span><span class="n">outline_shift_y</span><span class="p">(</span><span class="n">outline_AB</span><span class="p">,</span> <span class="n">y</span><span class="o">-</span><span class="n">offset</span><span class="p">,</span> <span class="n">y</span><span class="o">-</span><span class="n">coefficient</span><span class="p">)</span>
<span class="n">cnc25d_api</span><span class="o">.</span><span class="n">outline_shift_xy</span><span class="p">(</span><span class="n">outline_AB</span><span class="p">,</span> <span class="n">x</span><span class="o">-</span><span class="n">offset</span><span class="p">,</span> <span class="n">x</span><span class="o">-</span><span class="n">coefficient</span><span class="p">,</span> <span class="n">y</span><span class="o">-</span><span class="n">offset</span><span class="p">,</span> <span class="n">y</span><span class="o">-</span><span class="n">coefficient</span><span class="p">)</span>
<span class="n">cnc25d_api</span><span class="o">.</span><span class="n">outline_rotate</span><span class="p">(</span><span class="n">outline_AB</span><span class="p">,</span> <span class="n">center</span><span class="o">-</span><span class="n">x</span><span class="p">,</span> <span class="n">center</span><span class="o">-</span><span class="n">y</span><span class="p">,</span> <span class="n">rotation_angle</span><span class="p">)</span>
<span class="n">cnc25d_api</span><span class="o">.</span><span class="n">outline_close</span><span class="p">(</span><span class="n">outline_AB</span><span class="p">)</span>
<span class="n">cnc25d_api</span><span class="o">.</span><span class="n">outline_reverse</span><span class="p">(</span><span class="n">outline_AB</span><span class="p">)</span>
</pre></div>
</div>
<div class="section" id="outline-shift">
<h4>3.5.1. outline_shift<a class="headerlink" href="#outline-shift" title="Permalink to this headline">¶</a></h4>
<div class="line-block">
<div class="line"><tt class="docutils literal"><span class="pre">cnc_cut_outline.</span></tt> <strong>outline_shift_x(</strong> <em>list, x-offset, x-factor</em> <strong>)</strong></div>
<div class="line"><tt class="docutils literal"><span class="pre">cnc_cut_outline.</span></tt> <strong>outline_shift_y(</strong> <em>list, y-offset, y-factor</em> <strong>)</strong></div>
<div class="line"><tt class="docutils literal"><span class="pre">cnc_cut_outline.</span></tt> <strong>outline_shift_xy(</strong> <em>list, x-offset, x-factor, y-offset, y-factor</em> <strong>)</strong></div>
<div class="line-block">
<div class="line">Return a list that defines a sub-sequence of outline.</div>
</div>
</div>
<p>The definition an outline can be quiet long and tedious. It might be useful to split a long list of points into several small sequences and concatenate them into one big list using the <em>.append()</em> and <em>.extend()</em> methods. Often it happens that sub-sequence patterns appear several times in one outline either shifted or mirrored. The functions <em>outline_shift_x</em>, <em>outline_shift_y</em> and outline_shift_xy can be use to help the reuse of outline sub sequences. Let&#8217;s look at the following example.</p>
<img alt="_images/outline_with_repeated_sub_sequences.png" src="_images/outline_with_repeated_sub_sequences.png" />
<p>If we want to define this outline brutally, we must create a list of 28 points. But we can also define first the blue and the green sub-sequences, which are each 3 points and create the complete outline out of them:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="c"># We follow the points in the counter clock wise (CCW)</span>
<span class="n">green_sequence</span> <span class="o">=</span> <span class="p">[</span>
  <span class="p">[</span> <span class="mi">10</span><span class="p">,</span>  <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">],</span>
  <span class="p">[</span> <span class="mi">20</span><span class="p">,</span> <span class="mi">10</span><span class="p">,</span> <span class="mi">0</span><span class="p">],</span>
  <span class="p">[</span> <span class="mi">20</span><span class="p">,</span>  <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">]]</span>
<span class="n">blue_sequence</span> <span class="o">=</span> <span class="p">[</span>
  <span class="p">[</span>  <span class="mi">0</span><span class="p">,</span> <span class="mi">25</span><span class="p">,</span> <span class="mi">0</span><span class="p">],</span>
  <span class="p">[</span> <span class="mi">10</span><span class="p">,</span> <span class="mi">25</span><span class="p">,</span> <span class="mi">0</span><span class="p">],</span>
  <span class="p">[</span>  <span class="mi">0</span><span class="p">,</span> <span class="mi">20</span><span class="p">,</span> <span class="mi">0</span><span class="p">]]</span>
<span class="n">width</span> <span class="o">=</span> <span class="mi">100</span>
<span class="n">height</span> <span class="o">=</span> <span class="mi">80</span>
<span class="n">my_outline</span> <span class="o">=</span> <span class="p">[]</span>
<span class="n">my_outline</span><span class="o">.</span><span class="n">append</span><span class="p">([</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">])</span>
<span class="n">my_outline</span><span class="o">.</span><span class="n">extend</span><span class="p">(</span><span class="n">blue_sequence</span><span class="p">)</span>
<span class="n">my_outline</span><span class="o">.</span><span class="n">extend</span><span class="p">(</span><span class="n">outline_shift_x</span><span class="p">(</span><span class="n">blue_sequence</span><span class="p">,</span> <span class="n">width</span><span class="p">,</span> <span class="o">-</span><span class="mi">1</span><span class="p">))</span>
<span class="n">my_outline</span><span class="o">.</span><span class="n">append</span><span class="p">([</span><span class="n">width</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">])</span>
<span class="n">my_outline</span><span class="o">.</span><span class="n">extend</span><span class="p">(</span><span class="n">outline_shift_x</span><span class="p">(</span><span class="n">green_sequence</span><span class="p">,</span> <span class="n">width</span><span class="p">,</span> <span class="o">-</span><span class="mi">1</span><span class="p">))</span>
<span class="n">my_outline</span><span class="o">.</span><span class="n">extend</span><span class="p">(</span><span class="n">outline_shift_xy</span><span class="p">(</span><span class="n">green_sequence</span><span class="p">,</span> <span class="n">width</span><span class="p">,</span> <span class="o">-</span><span class="mi">1</span><span class="p">,</span> <span class="n">height</span><span class="p">,</span> <span class="o">-</span><span class="mi">1</span><span class="p">))</span>
<span class="n">my_outline</span><span class="o">.</span><span class="n">append</span><span class="p">([</span><span class="n">width</span><span class="p">,</span> <span class="n">height</span><span class="p">,</span> <span class="mi">0</span><span class="p">])</span>
<span class="n">my_outline</span><span class="o">.</span><span class="n">extend</span><span class="p">(</span><span class="n">outline_shift_xy</span><span class="p">(</span><span class="n">blue_sequence</span><span class="p">,</span> <span class="n">width</span><span class="p">,</span> <span class="o">-</span><span class="mi">1</span><span class="p">,</span> <span class="n">height</span><span class="p">,</span> <span class="o">-</span><span class="mi">1</span><span class="p">))</span>
<span class="n">my_outline</span><span class="o">.</span><span class="n">extend</span><span class="p">(</span><span class="n">outline_shift_y</span><span class="p">(</span><span class="n">blue_sequence</span><span class="p">,</span> <span class="n">height</span><span class="p">,</span> <span class="o">-</span><span class="mi">1</span><span class="p">))</span>
<span class="n">my_outline</span><span class="o">.</span><span class="n">append</span><span class="p">([</span><span class="mi">0</span><span class="p">,</span> <span class="n">height</span><span class="p">,</span> <span class="mi">0</span><span class="p">])</span>
<span class="n">my_outline</span><span class="o">.</span><span class="n">extend</span><span class="p">(</span><span class="n">outline_shift_y</span><span class="p">(</span><span class="n">green_sequence</span><span class="p">,</span> <span class="n">height</span><span class="p">,</span> <span class="o">-</span><span class="mi">1</span><span class="p">))</span>
<span class="n">my_outline</span><span class="o">.</span><span class="n">extend</span><span class="p">(</span><span class="n">green_sequence</span><span class="p">)</span>
</pre></div>
</div>
<p>This code is easier to maintain.</p>
</div>
<div class="section" id="outline-rotate">
<h4>3.5.2. outline_rotate<a class="headerlink" href="#outline-rotate" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python"><div class="highlight"><pre><span class="n">cnc25d_api</span><span class="o">.</span><span class="n">outline_rotate</span><span class="p">(</span><span class="n">outline_AB</span><span class="p">,</span> <span class="n">center</span><span class="o">-</span><span class="n">x</span><span class="p">,</span> <span class="n">center</span><span class="o">-</span><span class="n">y</span><span class="p">,</span> <span class="n">rotation_angle</span><span class="p">)</span>
<span class="k">return</span> <span class="n">outline_AB</span>
</pre></div>
</div>
<p>It applies a rotation of center (x,y) and angle <em>rotation_angle</em> to each points of the input outline.</p>
</div>
<div class="section" id="outline-close">
<h4>3.5.2. outline_close<a class="headerlink" href="#outline-close" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python"><div class="highlight"><pre><span class="n">cnc25d_api</span><span class="o">.</span><span class="n">outline_close</span><span class="p">(</span><span class="n">outline_AB</span><span class="p">)</span>
<span class="k">return</span> <span class="n">outline_AB</span>
</pre></div>
</div>
<p>If the input outline is open, it closes it with a straight line (from the end-point of the last segment to the first-point).</p>
</div>
<div class="section" id="outline-reverse">
<h4>3.5.3. outline_reverse<a class="headerlink" href="#outline-reverse" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python"><div class="highlight"><pre><span class="n">cnc25d_api</span><span class="o">.</span><span class="n">outline_reverse</span><span class="p">(</span><span class="n">outline_AB</span><span class="p">)</span>
<span class="k">return</span> <span class="n">outline_AB</span>
</pre></div>
</div>
<p>It reverses the order of the segments. If the outline is closed, that reverses its orientation (from CCW to CW or opposite). Notice that the <em>.reverse()</em> python method would not return a valid outline (format A or B) because of the <em>first-point</em> and the <em>middle-point</em> of arcs.</p>
</div>
</div>
</div>
<div class="section" id="cnc25d-outline-utilization">
<h2>4. Cnc25D outline utilization<a class="headerlink" href="#cnc25d-outline-utilization" title="Permalink to this headline">¶</a></h2>
<p>After getting a <em>Cnc25D format B outline</em> from the cnc_cut_outline() function, you probably want to use this outline in <a class="reference external" href="https://en.wikipedia.org/wiki/Comparison_of_CAD_editors_for_AEC">CAD</a> tools. The function <em>cnc25d_api.outline_arc_line()</em> lets you transform the <em>Cnc25D format B outline</em> into one of this four formats: <em>freecad</em>, <em>svgwrite</em>, <em>dxfwrite</em>, <em>tkinter</em>.</p>
<div class="highlight-python"><pre>cnc25d_api.outline_arc_line(outline_B, backend)
cnc25d_api.outline_circle((center-x, center-y), radius, backend)

with backend=['freecad', 'svgwrite', 'dxfwrite', 'tkinter']</pre>
</div>
<div class="section" id="freecad">
<h3>4.1. freecad<a class="headerlink" href="#freecad" title="Permalink to this headline">¶</a></h3>
<p><em>outline_arc_line(outline_B, &#8216;freecad&#8217;)</em> returns <em>FreeCAD Part.Shape</em> object that can be used easily in the classic <em>FreeCAD</em> workflow:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">my_part_shape</span> <span class="o">=</span> <span class="n">cnc25d_api</span><span class="o">.</span><span class="n">outline_arc_line</span><span class="p">(</span><span class="n">my_outline_B</span><span class="p">,</span> <span class="s">&#39;freecad&#39;</span><span class="p">)</span>
<span class="n">my_part_face</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">Face</span><span class="p">(</span><span class="n">Part</span><span class="o">.</span><span class="n">Wire</span><span class="p">(</span><span class="n">my_part_shape</span><span class="o">.</span><span class="n">Edges</span><span class="p">))</span>
<span class="n">my_part_solid</span> <span class="o">=</span> <span class="n">my_part_face</span><span class="o">.</span><span class="n">extrude</span><span class="p">(</span><span class="n">Base</span><span class="o">.</span><span class="n">Vector</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span><span class="mi">0</span><span class="p">,</span><span class="mi">20</span><span class="p">))</span>
</pre></div>
</div>
<p>Notice that <em>FreeCAD</em> conserve the <em>arc</em> geometrical entity during its complete workflow. So after extruding the outline, slicing the part and then projecting it again in a DXF file, you still get the <em>arcs</em> you have designed in your original outline.</p>
<p>The combination <em>outline_arc_line(cnc_cut_outline(), &#8216;freecad&#8217;)</em> is often used. So the <em>Cnc25D API</em> proposes this combination with the function <em>cnc25d_api.cnc_cut_outline_fc()</em>.</p>
<p>With this methodolgy you can create and extrude any outline made out of lines and arcs. But creating a <em>circle</em> outline is not directly possible. You need to create two consecutive arcs, which is not very convenient. If you want to create a circle (to extrude it into a cylinder), you can use the function <em>cnc25d_api.outline_circle((center-x, center-y), radius, &#8216;freecad&#8217;)</em>.</p>
</div>
<div class="section" id="svgwrite">
<h3>4.2. svgwrite<a class="headerlink" href="#svgwrite" title="Permalink to this headline">¶</a></h3>
<p>A <em>Cnc25D format B outline</em> is a 2D vectorial shape that can be transposed in a <a class="reference external" href="http://www.w3.org/Graphics/SVG/">SVG</a> file. <em>SVG file</em> is one of the usual input format for the 3-axis CNC tool chain. This snippet let you dump the <em>Cnc25D format B outline</em> in a <em>SVG</em> file:</p>
<div class="highlight-python"><pre>import svgwrite
my_outline_B = [ .. ]
object_svg = svgwrite.Drawing(filename = "my_ouline.svg")
svg_outline = cnc25d_api.outline_arc_line(my_outline_B, 'svgwrite')
for one_line_or_arc in svg_outline:
  object_svg.add(one_line_or_arc)
#one_svg_circle = cnc25d_api.outline_circle((100,100), 40, 'svgwrite') # create a circle
#object_svg.add(one_svg_circle)
object_svg.save()</pre>
</div>
<p><em>Cnc25D</em> relies on the <em>Python package</em> <a class="reference external" href="http://pythonhosted.org/svgwrite/">svgwrite</a> from <strong>mozman</strong>. Use <a class="reference external" href="http://inkscape.org/">Inkscape</a> to review the generated <em>SVG</em> file.</p>
<p><strong>Warning:</strong> The <a class="reference external" href="http://www.w3.org/Graphics/SVG/">SVG</a> format supports the <em>arc</em> graphical object but the Python package <a class="reference external" href="http://pythonhosted.org/svgwrite/">svgwrite</a> has not implemented yet the <em>arc</em> constructor. So <em>Cnc25D</em> transform each <em>arc</em> of the outline into a series of small segments. This might be an issue for certain <em>CNC tool chain</em> or for some designs.</p>
</div>
<div class="section" id="dxfwrite">
<h3>4.3. dxfwrite<a class="headerlink" href="#dxfwrite" title="Permalink to this headline">¶</a></h3>
<p>A <em>Cnc25D format B outline</em> is a 2D vectorial shape that can be transposed in a <a class="reference external" href="http://en.wikipedia.org/wiki/AutoCAD_DXF">DXF</a> file:</p>
<div class="highlight-python"><pre>import dxfwrite
my_outline_B = [ .. ]
object_dxf = DXFEngine.drawing("my_outline.dxf")
#object_dxf.add_layer("my_dxf_layer")
dxf_outline = cnc25d_api.outline_arc_line(my_outline_B, 'dxfwrite')
for one_line_or_arc in dxf_outline:
  object_dxf.add(one_line_or_arc)
#one_dxf_circle = cnc25d_api.outline_circle((100,100), 40, 'dxfwrite') # create a circle
#object_dxf.add(one_dxf_circle)
object_dxf.save()</pre>
</div>
<p><em>Cnc25D</em> relies on the <em>Python package</em> <a class="reference external" href="http://pythonhosted.org/svgwrite/">dxfwrite</a> from <strong>mozman</strong>. Use <a class="reference external" href="http://librecad.org">LibreCAD</a> to review the generated <em>DXF</em> file.</p>
<p><strong>Warning:</strong> Like previously, the <a class="reference external" href="http://en.wikipedia.org/wiki/AutoCAD_DXF">DXF</a> format supports the <em>arc</em> graphical object but the Python package <a class="reference external" href="http://pythonhosted.org/svgwrite/">dxfwrite</a> has not implemented yet the <em>arc</em> constructor. So <em>Cnc25D</em> transform each <em>arc</em> of the outline into a series of small segments. This might be an issue for certain <em>CNC tool chain</em> or for some designs.</p>
</div>
<div class="section" id="tkinter">
<h3>4.4. tkinter<a class="headerlink" href="#tkinter" title="Permalink to this headline">¶</a></h3>
<p>During the early phase of the design, you just need to view the outline (that still might be under-construction) without using the powerful <em>FreeCAD</em> or dumping files. This is the purpose of the <em>Tkinter GUI</em>. Check the design example <em>cnc25d_api_example.py</em> generated by the binary <em>cnc25d_example_generator.py</em> or check the file <em>cnc25d/tests/cnc25d_api_macro.py</em> to see how to implement this small <em>graphic user interface</em>.</p>
</div>
</div>
<div class="section" id="working-with-freecad">
<h2>5. Working with FreeCAD<a class="headerlink" href="#working-with-freecad" title="Permalink to this headline">¶</a></h2>
<div class="section" id="import-freecad">
<h3>5.1. import FreeCAD<a class="headerlink" href="#import-freecad" title="Permalink to this headline">¶</a></h3>
<div class="line-block">
<div class="line"><tt class="docutils literal"><span class="pre">cnc25d_api.</span></tt> <strong>importing_freecad()</strong></div>
<div class="line-block">
<div class="line">Modify the global variable <em>sys.path</em>.</div>
</div>
</div>
<p>FreeCAD comes with Python modules. But these FreeCAD modules are not installed in one of the standard directories. You will find the Python FreeCAD modules in a directory such as <em>/usr/lib/freecad/lib</em>. To use FreeCAD from a Python script, you need either to set the PYTHONPATH system environment variable or to extend the sys.path Python variable.</p>
<p>Because you need to import FreeCAD at each beginning of scripts, this task as been implemented in the module <em>cnc25d_api.py</em> that is installed in a standard location. So, after installing Cnc25D, to use the FreeCAD modules, you only need to add those lines at the beginning of your Python script:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="kn">from</span> <span class="nn">cnc25d</span> <span class="kn">import</span> <span class="n">cnc25d_api</span>
<span class="n">cnc25d_api</span><span class="o">.</span><span class="n">importing_freecad</span><span class="p">()</span>
</pre></div>
</div>
<p>The function <em>importing_freecad()</em> looks for the FreeCAD modules using a location list. If the function <em>importing_freecad()</em> doesn&#8217;t manage to find FreeCAD on your system, you may need to edit the module <em>importing_freecad.py</em> and add the path to the FreeCAD modules to the <em>FREECADPATH</em> list.</p>
</div>
<div class="section" id="place-plank">
<h3>5.2. place_plank()<a class="headerlink" href="#place-plank" title="Permalink to this headline">¶</a></h3>
<div class="line-block">
<div class="line"><tt class="docutils literal"><span class="pre">cnc_cut_outline.</span></tt> <strong>place_plank(</strong> <em>FreeCAD.Part.Object, x-size, y-size, z-size, flip, orientation, x-position, y-position, z-posistion</em> <strong>)</strong></div>
<div class="line-block">
<div class="line">Return a <em>FreeCAD.Part.Object</em></div>
</div>
</div>
<p>FreeCAD provides the usual <em>rotate</em> and <em>translate</em> methods to place an object in a construction-assembly. Even if those methods are mathematically straight forward, they might require many <em>tries and errors</em> to find out the correct rotation to apply to an object to place it correctly in an assembly. The <em>place_plank()</em> function provides an alternative to the <em>rotate</em> method when you want to place a object in a cuboid assembly.</p>
<p>To help positioning object we have the following conventions:</p>
<ul class="simple">
<li>The largest size of an object defines the <em>main axis</em> of the object.</li>
<li>The second largest size of an object defines the <em>second axis</em> of the object.</li>
<li>During the object construction, we choose the X axis as <em>main axis</em> and the Y axis as <em>second axis</em>.</li>
</ul>
<p>A cuboid assembly is a construction where most of the objects have their <em>main axis</em> parallel to the X, Y or Z-axis.
To place an object, construed with the above conventions, in a cuboid assembly, you can define the rotation of the object with two natural parameters:</p>
<ul class="simple">
<li>the orientation of the <em>main and second axis</em>. There are just six possibilities: &#8216;xy&#8217;, &#8216;xz&#8217;, &#8216;yx&#8217;, &#8216;yz&#8217;, &#8216;zx&#8217; and &#8216;zy&#8217;. For example, &#8216;yx&#8217; means that the <em>main axis</em> of the object is parallel to the Y-axis of the reference frame and the <em>second axis</em> of the object is parallel to the X-axis.</li>
<li>the flip of the object. After defining the orientation of the <em>main axis</em> and <em>second axis</em>, there are still four possibilities called <em>flip</em>: &#8216;identity&#8217;, &#8216;x-flip&#8217;, &#8216;y-flip&#8217; and &#8216;z-flip&#8217;.</li>
</ul>
<p>The <em>place_plank()</em> function uses this approach to place a object in an cuboid assembly. To realize flip and orientation, the <em>place_plank()</em> function needs to know the sizes along X, Y and Z of the object. Those sizes are virtual and you can play with them for your convenience.</p>
<img alt="_images/object_definition_and_flip.png" src="_images/object_definition_and_flip.png" />
<p>A physical object can be defined in several ways respecting our <em>main and second axis</em> conventions. The choice of the definition influences the behavior of the <em>flip</em>. Knowing that, choose the most convenient definitions for your design.</p>
<p>Look at the <a class="reference internal" href="place_plank.html"><em>Plank Positioning</em></a> chapter to get more explaination on rotation, orientation and flip transformations.</p>
</div>
<div class="section" id="drawing-export">
<h3>5.3. Drawing export<a class="headerlink" href="#drawing-export" title="Permalink to this headline">¶</a></h3>
<p><strong>FreeCAD</strong> provides very efficient methods for 3D export such as <em>.exportBrep()</em>, <em>.exportStep()</em> or <em>.exportStl()</em>. It also provides full customizable 2D export methods such as <em>.slice()</em> and <em>projectToDXF()</em>. <strong>Cnc25D</strong> provides simple functions that covers the most standard usage of the 2D export.</p>
<div class="section" id="cut-export-as-dxf">
<h4>5.3.1. Cut export as DXF<a class="headerlink" href="#cut-export-as-dxf" title="Permalink to this headline">¶</a></h4>
<div class="line-block">
<div class="line"><tt class="docutils literal"><span class="pre">export_2d.</span></tt> <strong>export_to_dxf(</strong> <em>FreeCAD.Part.Object, FreeCAD.Base.Vector, depth, path</em> <strong>)</strong></div>
<div class="line-block">
<div class="line">Write the <a class="reference external" href="http://en.wikipedia.org/wiki/AutoCAD_DXF">DXF</a> file <em>path</em>.</div>
</div>
</div>
<p>The <em>export_to_dxf()</em> function performs two successive operations:</p>
<ul class="simple">
<li>It cuts a slice of the <em>FreeCAD.Part.Object</em> according to the direction <em>FreeCAD.Base.Vector</em> and the <em>depth</em>.</li>
<li>It writes the <a class="reference external" href="http://en.wikipedia.org/wiki/AutoCAD_DXF">DXF</a> file <em>path</em> containing the projection of the slice.</li>
</ul>
<p>If you are designing a 2.5D part, this function is useful to get the <a class="reference external" href="http://en.wikipedia.org/wiki/AutoCAD_DXF">DXF</a> file that will be used by the CNC workflow.</p>
<p>Usage example:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">export_2d</span><span class="o">.</span><span class="n">export_to_dxf</span><span class="p">(</span><span class="n">my_part_solid</span><span class="p">,</span> <span class="n">Base</span><span class="o">.</span><span class="n">Vector</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span><span class="mi">0</span><span class="p">,</span><span class="mi">1</span><span class="p">),</span> <span class="mf">1.0</span><span class="p">,</span> <span class="s">&quot;my_part.dxf&quot;</span><span class="p">)</span>
</pre></div>
</div>
</div>
<div class="section" id="cut-export-as-svg">
<h4>5.3.2. Cut export as SVG<a class="headerlink" href="#cut-export-as-svg" title="Permalink to this headline">¶</a></h4>
<div class="line-block">
<div class="line"><tt class="docutils literal"><span class="pre">export_2d.</span></tt> <strong>export_to_svg(</strong> <em>FreeCAD.Part.Object, FreeCAD.Base.Vector, depth, path</em> <strong>)</strong></div>
<div class="line-block">
<div class="line">Write the <a class="reference external" href="http://www.w3.org/Graphics/SVG/">SVG</a> file <em>path</em>.</div>
</div>
</div>
<p>The <em>export_to_svg()</em> function performs the same operations as <em>export_to_dxf()</em> except it write a <a class="reference external" href="http://www.w3.org/Graphics/SVG/">SVG</a> file.</p>
<p>Usage example:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">export_2d</span><span class="o">.</span><span class="n">export_to_svg</span><span class="p">(</span><span class="n">my_part_solid</span><span class="p">,</span> <span class="n">Base</span><span class="o">.</span><span class="n">Vector</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span><span class="mi">0</span><span class="p">,</span><span class="mi">1</span><span class="p">),</span> <span class="mf">1.0</span><span class="p">,</span> <span class="s">&quot;my_part.svg&quot;</span><span class="p">)</span>
</pre></div>
</div>
<p><strong>Warning:</strong> The function <em>export_to_svg()</em> only works when it is used in a script run from the FreeCAD GUI. This is because of a current limitation of the FreeCAD library function <em>Drawing.projectToSVG()</em>.</p>
</div>
<div class="section" id="xyz-scanning">
<h4>5.3.3. XYZ scanning<a class="headerlink" href="#xyz-scanning" title="Permalink to this headline">¶</a></h4>
<div class="line-block">
<div class="line"><tt class="docutils literal"><span class="pre">export_2d.</span></tt> <strong>export_xyz_to_dxf(</strong> <em>FreeCAD.Part.Object, x-size, y-size, z-size, x-list, y-list, z-list, path</em> <strong>)</strong></div>
<div class="line-block">
<div class="line">Write the <a class="reference external" href="http://en.wikipedia.org/wiki/AutoCAD_DXF">DXF</a> file <em>path</em>.</div>
</div>
</div>
<p>The <em>export_xyz_to_dxf()</em> function cuts in many slices the <em>FreeCAD.Part.Object</em> according to the three directions of the reference frame axis X, Y and Z. The depth of the slices are provided by the three argument lists <em>x-list</em>, <em>y-list</em> and <em>z-list</em>. All the slices are placed in the plan XY and are written in the <a class="reference external" href="http://en.wikipedia.org/wiki/AutoCAD_DXF">DXF</a> file <em>path</em>.</p>
<p>The result looks like a medical scan. This is a more comfortable and readable document than the CAD tradition 3 views projections. This helps to show up weaknesses of designs if you choose good slices.</p>
<img alt="_images/export_xyz_to_dxf.png" src="_images/export_xyz_to_dxf.png" />
<p>Usage example:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">xy_slice_list</span> <span class="o">=</span> <span class="p">[</span> <span class="mf">0.1</span><span class="o">+</span><span class="mi">20</span><span class="o">*</span><span class="n">i</span> <span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="mi">12</span><span class="p">)</span> <span class="p">]</span>
<span class="n">xz_slice_list</span> <span class="o">=</span> <span class="p">[</span> <span class="mf">0.1</span><span class="o">+</span><span class="mi">20</span><span class="o">*</span><span class="n">i</span> <span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="mi">9</span><span class="p">)</span> <span class="p">]</span>
<span class="n">yz_slice_list</span> <span class="o">=</span> <span class="p">[</span> <span class="mf">0.1</span><span class="o">+</span><span class="mi">20</span><span class="o">*</span><span class="n">i</span> <span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="mi">9</span><span class="p">)</span> <span class="p">]</span>
<span class="n">export_2d</span><span class="o">.</span><span class="n">export_xyz_to_dxf</span><span class="p">(</span><span class="n">my_assembly</span><span class="p">,</span> <span class="mf">180.0</span><span class="p">,</span> <span class="mf">180.0</span><span class="p">,</span> <span class="mf">240.0</span><span class="p">,</span> <span class="n">xy_slice_list</span><span class="p">,</span> <span class="n">xz_slice_list</span><span class="p">,</span> <span class="n">yz_slice_list</span><span class="p">,</span> <span class="s">&quot;my_assembly.dxf&quot;</span><span class="p">)</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>


      </div>
      <div class="bottomnav">
      
        <p>
        «&#160;&#160;<a href="cnc25d_presentation.html">Cnc25D Presentation</a>
        &#160;&#160;::&#160;&#160;
        <a class="uplink" href="index.html">Contents</a>
        &#160;&#160;::&#160;&#160;
        <a href="box_wood_frame_design.html">Box Wood Frame Design</a>&#160;&#160;»
        </p>

      </div>

    <div class="footer">
        &copy; Copyright 2013, charlyoleg.
      Created using <a href="http://sphinx-doc.org/">Sphinx</a> 1.2b1.
    </div>
  </body>
</html>